apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: rifkiadrn-xyz-tls
spec:
  secretName: rifkiadrn-xyz
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: rifkiadrn.xyz
  dnsNames:
    - rifkiadrn.xyz
    - www.rifkiadrn.xyz
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - rifkiadrn.xyz
          - www.rifkiadrn.xyz
